### PR TITLE
(FM-7550) Edit test lib to allow for empty exclusions

### PR DESCRIPTION
**Pull request by willmeek**

### CODE REVIEW

**Review by Thomas-Franklin — COMMENTED** [review]
Happy to merge, although is the nil check really needed? 

Since if there is no harness_class with `version_unsupported_properties` or `unsupported_properties` then it will be an empty hash/array respectively which means the `.delete` etc was never performed, unless there is a test harness which we have missed, or one which returns nil maybe instead of a hash/array?

**Comment by willmeek** [comment]
Cisco test_ace needs this as unsupported_properties returns nil on the 9k

**Comment by Thomas-Franklin** [comment]
> Cisco test_ace needs this as unsupported_properties returns nil

Ah others just return an empty array, but happy to merge this as it makes it a bit more robust. 👍

**Comment by willmeek** [comment]
Belt n braces and all that

**Pull request merged**
