### PR TITLE
(MODULES-8232) Unset functionality for syslog_settings

### PR DESCRIPTION
**Pull request by willmeek**

### CODE REVIEW

**Review by Thomas-Franklin — CHANGES_REQUESTED** [review]
A test will need added for `canonicalize` and the existing (https://github.com/puppetlabs/cisco-network-puppet-module/pull/97/files#diff-7f447dea7ed49e631d6f09e6a477f928R341) test will need removed as it is no longer required.

**Comment by Thomas-Franklin** [comment]
Requires https://github.com/puppetlabs/netdev_stdlib/pull/57 to be merged first

**Comment by Thomas-Franklin** [comment]
puppetlabs/netdev_stdlib#57 has been merged, buth this has some conflicts. Once they have been resolved I'll verify the changes and get this merged :-)

**Comment by willmeek** [comment]
Rebased and resolved conflicts

**Comment by willmeek** [comment]
@Thomas-Franklin This should be ready for merge?

**Review by Thomas-Franklin — APPROVED** [review]

**Pull request merged**
