### PR TITLE
(FM-7451) Convert netdev radius to agentless

### PR DESCRIPTION
**Pull request by willmeek**
Note that existing radius provider functionality seems to have no affect.
Enable is the only field and is not used.
Radius itself does not look to be togglable on the device.
No-op for create/update/delete.

### CODE REVIEW

**Comment by willmeek** [comment]
Very strange PR. It looks like Radius as-is does not do anything at all. So I've reflected that. Ideally it wouldn't even be there, as per IOS. 'radius' as a whole does not seem to be something that is toggled on/off but rather individual features are set (as per radius_global etc)

**Comment by Thomas-Franklin** [comment]
> Very strange PR. It looks like Radius as-is does not do anything at all. So I've reflected that. Ideally it wouldn't even be there, as per IOS. 'radius' as a whole does not seem to be something that is toggled on/off but rather individual features are set (as per radius_global etc)

For completeness as the type is referred to in the docs we might as well convert it 👍

**Comment by da-ar** [comment]
Perhaps Radius should be flagged for removal from netdev_stdlib?

**Comment by Thomas-Franklin** [comment]
> Perhaps Radius should be flagged for removal from netdev_stdlib?

`aristaeos` also uses netdev_stdlib - possibly radius is of more use to them?

**Comment by willmeek** [comment]
As much as it seems to be no use to the Ciscos I wouldn't want to start ripping stuff out of netdev_stdlib

Perhaps a Q for @shermdog ?

**Comment by shermdog** [comment]
We may be able to deprecate the top level radius and tacacs types.  I can't find the history on why they were originally put in.  NETDEV-32 was opened a while back to look into this.

**Pull request merged**
